"""Update tables

Revision ID: 7d8d251f6e8d
Revises: ed42765b1d4e
Create Date: 2021-06-10 16:48:13.988415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8d251f6e8d'
down_revision = 'ed42765b1d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('holdings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
