"""Add relationships and updates.

Revision ID: ed42765b1d4e
Revises: 19fa01003a94
Create Date: 2021-06-09 21:21:15.562775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed42765b1d4e'
down_revision = '19fa01003a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'holdings', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_column('holdings', 'user_id')
    # ### end Alembic commands ###
